version: '3'

services:
  serasa-app-api-pg:
    container_name: serasa-app-api-pg
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=serasapp
