import { RootLayout } from '@/views/layouts/RootLayout'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" className="h-full">
      <body className="h-full">
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}
